### ISSUE TITLE
(Summary) Exceeds Expectations

### ISSUE THREAD

**Issue by CharlesDLandau** [jjanenda/SQL_Scratch_Capstone_TurnIn_JJanenda#2]
## Rubric Score
 
### Criteria 1: Report: Are conclusions clear and supported by evidence in all eight answers?
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Very good, you have clear exposition with evidence. See my issue on the Facebook ads, but it's too minor to bump this down a grade. Nice visual mark.
 
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Very good, you had correct outputs across the board. I really enjoyed the custom queries.
 
### Criteria 3: Query Formatting
* _Score Level:_ 4 (Meets Expectations)
* _Comment(s):_ Minor violations, see the  issue
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Very good explanation of the core concepts, custom queries and good exposition all support or illustrate the multi-touch marketing concepts.

 ### Overall Score: 16/16
Way to go! I'm a big fan of your presentation - very attractive visual mark, good organization. Your queries are mostly clean and overall technically correct. Exceeds expectations across the board.

**Comment by jjanenda** [comment]
Charles, greatly appreciate your feedback and the time you took to review the project for me.  The Query formatting one hurts, as I had asked way back in Unit 3 if capitalization and indents 'mattered'.  I was told they were only for 'readability'.  It was only when I was done with the entire project and reading the Rubric that I saw reference to the style guide.  At that point, I tried to do a find and replace in Word to fix all the issues - I must have missed the 'AS' one.  I just went back and looked and apparently there were 4 that I didn't see.  Were there any others??

![image](https://user-images.githubusercontent.com/39015404/40943988-1f1897ea-6821-11e8-9c04-f4648afc9367.png)

**Comment by CharlesDLandau** [comment]
I think not - AS errors were the ones that jumped out at me.

**Comment by jjanenda** [comment]
So I looked at this once more and there are TWO instances where 'AS' appears as 'as' in the queries I was assigned to do.    That's 2 words out of 530, or 4 characters out of 2,886.  The rubric for Query Formatting says that Exceeds Expectations qualification is 'Queries are formatted according
to the linked style guide' and Meets Expectations is that 'Queries adhere to at least 7 rules
of the style guide.' (there are 9).  Seems like the points off for 4 characters is a bit harsh.  What do you say we change that to 4 - Exceeds Expectations?

**Comment by CharlesDLandau** [comment]
On review, my recollection was bad in the last comment. There are a few other iffy decisions.

Capitalizing the first letter of a single word is technically snake case I guess...
https://github.com/jjanenda/SQL_Scratch_Capstone_TurnIn_JJanenda/blob/7a4a9e4ce54f84efee2ec2dac8733fda72f8b858/sql.code.txt#L74-L76

Do we need `*` here? I don't see the output so it's hard to say.
https://github.com/jjanenda/SQL_Scratch_Capstone_TurnIn_JJanenda/blob/7a4a9e4ce54f84efee2ec2dac8733fda72f8b858/sql.code.txt#L112

But these aren't *necessarily* errors...and you've certainly spent the time grappling with the style guide, so I'll bump it up the extra point.
